# Generated by Django 5.2.5 on 2025-08-21 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('reply', 'Reply'), ('mention', 'Mention')], help_text='The type of action that triggered this notification', max_length=50)),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, help_text='Custom message for the notification')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the recipient has read this notification')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the notification was created')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was marked as read', null=True)),
                ('actor', models.ForeignKey(help_text='The user who performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='actor_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(help_text='The user who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'unique_together': {('recipient', 'actor', 'verb', 'target_content_type', 'target_object_id')},
            },
        ),
    ]
